spring.application.name=nexushr-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/nexushr
spring.datasource.username=postgres
spring.datasource.password=8223

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
