apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexushr-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexushr-backend
  template:
    metadata:
      labels:
        app: nexushr-backend
    spec:
      containers:
        - name: nexushr-backend
          image: nexushr-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/nexushr

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexushr-secret
                  key: postgres-password

            - name: SPRING_DATA_REDIS_HOST
              value: host.docker.internal

            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
